---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Linux setup dependency..
  image: xyzuan/xdocker:latest
  environment:
    TG_TOKEN:
      from_secret: TG_TOKEN
    TG_CHAT_ID:
      from_secret: TG_CHAT_ID
  commands:
  - bash setup.sh
- name: Start syncing..
  image: xyzuan/xdocker:latest
  environment:
    TG_TOKEN:
      from_secret: TG_TOKEN
    TG_CHAT_ID:
      from_secret: TG_CHAT_ID
  commands:
  - bash sync.sh
- name: Start Compiling..
  image: xyzuan/xdocker:latest
  environment:
    TG_TOKEN:
      from_secret: TG_TOKEN
    TG_CHAT_ID:
      from_secret: TG_CHAT_ID
  commands:
  - bash build.sh
