---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Start syncing && Compiling
  image: brock5555/recovery
  environment:
       MANIFEST: https://github.com/Palladium-OS/platform_manifest.git -b 11
       DEVICE: rosy
       BRANCH: eleven
       DT_LINK: https://github.com/AnGgIt88/device_xiaomi_rosy
       DT_PATH: device/xiaomi/rosy
       VT_LINK: https://github.com/AnGgIt88/xd_vendor_xiaomi_rosy
       VT_BRANCH: eleven
       VT_PATH: vendor/xiaomi/rosy
       KT_LINK: https://github.com/AnGgIt88/Finix_kernel-4.9-rosy
       KT_BRANCH: eleven
       KT_PATH: kernel/xiaomi/rosy
       TC_LINK: https://github.com/AnGgIt86/Finix-Clang
       TC_BRANCH: master
       TC_PATH: prebuilts/clang/host/linux-x86/clang-Finix
  commands:
  - bash build.sh
