---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Start syncing && Compiling
  image: brock5555/recovery
  environment:
       MANIFEST: git://github.com/DotOS/manifest.git -b dot11
       DEVICE: rosy
       BRANCH: dot
       DT_LINK: https://github.com/arulebin/device_xiaomi_rosy
       DT_PATH: device/xiaomi/rosy
       VT_LINK: https://github.com/Pulkit077/vendor_xiaomi_rosy
       VT_BRANCH: eleven
       VT_PATH: vendor/xiaomi/rosy
       KT_LINK: https://github.com/AnGgIt88/finix_kernel_xiaomi_rosy
       KT_BRANCH: eleven
       KT_PATH: kernel/xiaomi/rosy
       TC_LINK: https://github.com/AnGgIt86/arm64-gcc
       TC_BRANCH: gcc-master
       TC_PATH: prebuilts/gcc/linux-x86/aarch64/aarch64-elf
       TC32_LINK: https://github.com/AnGgIt86/gcc-arm
       TC32_BRANCH: gcc-master
       TC32_PATH: prebuilts/gcc/linux-x86/arm/arm-eabi
       DRONE_TIMEOUT: 9h
  commands:
  - bash build.sh
